# Generated by Django 3.0.5 on 2020-08-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.FloatField(default=0.0),
        ),
    ]
